### ISSUE TITLE
jetToolbox_91X_v1 tag error in CMSSW_9_4_X release

### ISSUE THREAD

**Issue by scarletnorberg** [cms-jet/JetToolbox#55] opened 2018-02-15 22:43 UTC
I am currently working in a CMSSW_9_4_X release and I have checked out the jetToolbox_91X_v1 tag of the JetToolbox. This was the latest recommended version on the JetToolbox twiki. However, when running the toolbox I get this error:

----- Begin Fatal Exception 15-Feb-2018 12:13:42 CST-----------------------
An exception of category ‘ConfigFileReadError’ occurred while
   [0] Processing the python configuration file named treeMaker_stopRA2.py
Exception Message:
python encountered the error: <type ‘exceptions.ImportError’>
cannot import name hepTopTagPFJetsCHS
----- End Fatal Exception --------

I checked through the CMSSW_9_4_X code base on GitHub and found that hepTopTagPFJetsCHS is no longer available. Is there a recommended workaround? Will a 94X version of the JetToolbox be available soon?

**Comment by rappoccio** [comment] 2018-02-16 14:31
We haven't had a chance to update the jet toolbox to 94x. The primary developer is Alejandro who is busy writing his thesis.

**Comment by kpedro88** [comment] 2018-02-27 20:19
@scarletnorberg and I made a fork and fixed it to work in 94X (as far as we can tell):
https://github.com/TreeMaker/JetToolbox/tree/jetToolbox_94X

However, there's no 94X branch here to send a PR.

**Comment by rappoccio** [comment] 2018-02-27 20:58
@kpedro88 thanks, I made a branch:
https://github.com/cms-jet/JetToolbox/tree/jetToolbox_94x

**Comment by rappoccio** [comment] 2018-02-27 20:59
@kpedro88 hang on, I am being inconsistent with "94x" versus "94X". I will fix.

**Comment by rappoccio** [comment] 2018-02-27 21:01
I think you have a line indent problem:

https://github.com/cms-jet/JetToolbox/compare/jetToolbox_94X...TreeMaker:jetToolbox_94X#diff-f1fc8e7a8a193e13cf51904bafa14b26R193

**Comment by kpedro88** [comment] 2018-02-27 21:02
@rappoccio would be better to start the 94X branch from the 91X branch rather than master

**Comment by kpedro88** [comment] 2018-02-27 21:04
I think the apparent indentation problem is due to mixing of tabs and spaces, which is a python no-no that predates any of my modifications in that file

**Comment by rappoccio** [comment] 2018-02-27 21:13
@kpedro88 OK I based it on 91x now. 

Yes, looks like there are some mixed tabs and spaces. I don't think I can merge this automatically if the indent is there.

**Comment by kpedro88** [comment] 2018-02-27 21:23
the problem is actually caused by some other 94X-related PRs that were merged in the 91X branch after my branch diverged. rebasing to handle appropriately

**Comment by kpedro88** [comment] 2018-02-27 21:25
see #56

**Comment by rappoccio** [comment] 2018-02-27 21:33
OK done!
Sal

**Closed** 2018-12-19 17:18 UTC
